# Generated by Django 4.1.2 on 2022-10-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_branch',
            field=models.CharField(default='cse', max_length=10),
        ),
    ]
